server:
  port: 8081
spring:
  application:
    name: DataManager
  kafka:
    bootstrap-servers: localhost:9092 # Адрес брокера Kafka
    consumer:
      group-id: my-group # Уникальная группа потребителей
      auto-offset-reset: earliest # Читать с самого начала топика
      enable-auto-commit: true # Авто-подтверждать полученные сообщения
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false # По желанию, отключить DDL auto-generation
    open-in-view: false # Улучшение производительности, отключает Lazy loading в веб-запросах
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/DataGuardian
    username: postgres
    password: 1703
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE