server:
  port: 8080
spring:
  application:
    name: CRMBusinessHubKt
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      reconnect-backoff-max: 30000
      retry:
        backoff: ms=10000
logging:
  level:
    org:
      springframework.web: DEBUG
      apache.kafka:
        clients=INFO:
service:
  dm-url: http://localhost:8081/dm/client